package info.korzeniowski.walletplus.model.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenCategoryDaoConfig;
    private final DaoConfig greenRecordDaoConfig;

    private final GreenCategoryDao greenCategoryDao;
    private final GreenRecordDao greenRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenCategoryDaoConfig = daoConfigMap.get(GreenCategoryDao.class).clone();
        greenCategoryDaoConfig.initIdentityScope(type);

        greenRecordDaoConfig = daoConfigMap.get(GreenRecordDao.class).clone();
        greenRecordDaoConfig.initIdentityScope(type);

        greenCategoryDao = new GreenCategoryDao(greenCategoryDaoConfig, this);
        greenRecordDao = new GreenRecordDao(greenRecordDaoConfig, this);

        registerDao(GreenCategory.class, greenCategoryDao);
        registerDao(GreenRecord.class, greenRecordDao);
    }
    
    public void clear() {
        greenCategoryDaoConfig.getIdentityScope().clear();
        greenRecordDaoConfig.getIdentityScope().clear();
    }

    public GreenCategoryDao getGreenCategoryDao() {
        return greenCategoryDao;
    }

    public GreenRecordDao getGreenRecordDao() {
        return greenRecordDao;
    }

}
