package info.korzeniowski.walletplus.model.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import info.korzeniowski.walletplus.model.greendao.CategoryG;
import info.korzeniowski.walletplus.model.greendao.RecordG;

import info.korzeniowski.walletplus.model.greendao.CategoryGDao;
import info.korzeniowski.walletplus.model.greendao.RecordGDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryGDaoConfig;
    private final DaoConfig recordGDaoConfig;

    private final CategoryGDao categoryGDao;
    private final RecordGDao recordGDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryGDaoConfig = daoConfigMap.get(CategoryGDao.class).clone();
        categoryGDaoConfig.initIdentityScope(type);

        recordGDaoConfig = daoConfigMap.get(RecordGDao.class).clone();
        recordGDaoConfig.initIdentityScope(type);

        categoryGDao = new CategoryGDao(categoryGDaoConfig, this);
        recordGDao = new RecordGDao(recordGDaoConfig, this);

        registerDao(CategoryG.class, categoryGDao);
        registerDao(RecordG.class, recordGDao);
    }
    
    public void clear() {
        categoryGDaoConfig.getIdentityScope().clear();
        recordGDaoConfig.getIdentityScope().clear();
    }

    public CategoryGDao getCategoryGDao() {
        return categoryGDao;
    }

    public RecordGDao getRecordGDao() {
        return recordGDao;
    }

}
