package info.korzeniowski.walletplus.model.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table Wallet.
 */
public class GreenWallet {

    private Long id;
    private Long accountId;
    private String name;
    private String description;
    private Double amount;
    private Integer type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GreenWallet() {
    }

    public GreenWallet(Long id) {
        this.id = id;
    }

    public GreenWallet(Long id, Long accountId, String name, String description, Double amount, Integer type) {
        this.id = id;
        this.accountId = accountId;
        this.name = name;
        this.description = description;
        this.amount = amount;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
