package info.korzeniowski.walletplus.model.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Wallet.
 */
public class GreenWallet {

    private Long id;
    private Long accountId;
    /** Not-null value. */
    private String name;
    private double initialAmount;
    private Double currentAmount;
    private int type;

    public GreenWallet() {
    }

    public GreenWallet(Long id) {
        this.id = id;
    }

    public GreenWallet(Long id, Long accountId, String name, double initialAmount, Double currentAmount, int type) {
        this.id = id;
        this.accountId = accountId;
        this.name = name;
        this.initialAmount = initialAmount;
        this.currentAmount = currentAmount;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public double getInitialAmount() {
        return initialAmount;
    }

    public void setInitialAmount(double initialAmount) {
        this.initialAmount = initialAmount;
    }

    public Double getCurrentAmount() {
        return currentAmount;
    }

    public void setCurrentAmount(Double currentAmount) {
        this.currentAmount = currentAmount;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

}
