package info.korzeniowski.walletplus.model.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import info.korzeniowski.walletplus.model.Wallet;
// KEEP INCLUDES END


/**
 * Entity mapped to table Wallet.
 */
public class GreenWallet {

    private Long id;
    private Long accountId;
    /** Not-null value. */
    private String name;
    private Double amount;
    private int type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GreenWallet() {
    }

    public GreenWallet(Long id) {
        this.id = id;
    }

    public GreenWallet(Long id, Long accountId, String name, Double amount, int type) {
        this.id = id;
        this.accountId = accountId;
        this.name = name;
        this.amount = amount;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    public GreenWallet(Wallet wallet) {
        setId(wallet.getId());
        setName(wallet.getName());
        setType(wallet.getType().ordinal());
        setAmount(wallet.getAmount());
    }
    // KEEP METHODS END

}
