package info.korzeniowski.walletplus.model.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import info.korzeniowski.walletplus.model.greendao.GreenCategory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table Category.
*/
public class GreenCategoryDao extends AbstractDao<GreenCategory, Long> {

    public static final String TABLENAME = "Category";

    /**
     * Properties of entity GreenCategory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ParentId = new Property(1, Long.class, "parentId", false, "PARENT_ID");
        public final static Property AccountId = new Property(2, Long.class, "accountId", false, "ACCOUNT_ID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Type = new Property(4, Integer.class, "type", false, "TYPE");
    };

    private DaoSession daoSession;

    private Query<GreenCategory> greenAccount_GreenCategoryListQuery;
    private Query<GreenCategory> greenCategory_ChildrenQuery;

    public GreenCategoryDao(DaoConfig config) {
        super(config);
    }
    
    public GreenCategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'Category' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PARENT_ID' INTEGER," + // 1: parentId
                "'ACCOUNT_ID' INTEGER," + // 2: accountId
                "'NAME' TEXT NOT NULL UNIQUE ," + // 3: name
                "'TYPE' INTEGER);"); // 4: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'Category'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GreenCategory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long parentId = entity.getParentId();
        if (parentId != null) {
            stmt.bindLong(2, parentId);
        }
 
        Long accountId = entity.getAccountId();
        if (accountId != null) {
            stmt.bindLong(3, accountId);
        }
        stmt.bindString(4, entity.getName());
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(5, type);
        }
    }

    @Override
    protected void attachEntity(GreenCategory entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GreenCategory readEntity(Cursor cursor, int offset) {
        GreenCategory entity = new GreenCategory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // parentId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // accountId
            cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4) // type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GreenCategory entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setParentId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setAccountId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setName(cursor.getString(offset + 3));
        entity.setType(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GreenCategory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GreenCategory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "greenCategoryList" to-many relationship of GreenAccount. */
    public List<GreenCategory> _queryGreenAccount_GreenCategoryList(Long accountId) {
        synchronized (this) {
            if (greenAccount_GreenCategoryListQuery == null) {
                QueryBuilder<GreenCategory> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AccountId.eq(null));
                greenAccount_GreenCategoryListQuery = queryBuilder.build();
            }
        }
        Query<GreenCategory> query = greenAccount_GreenCategoryListQuery.forCurrentThread();
        query.setParameter(0, accountId);
        return query.list();
    }

    /** Internal query to resolve the "children" to-many relationship of GreenCategory. */
    public List<GreenCategory> _queryGreenCategory_Children(Long parentId) {
        synchronized (this) {
            if (greenCategory_ChildrenQuery == null) {
                QueryBuilder<GreenCategory> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ParentId.eq(null));
                greenCategory_ChildrenQuery = queryBuilder.build();
            }
        }
        Query<GreenCategory> query = greenCategory_ChildrenQuery.forCurrentThread();
        query.setParameter(0, parentId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGreenCategoryDao().getAllColumns());
            builder.append(" FROM Category T");
            builder.append(" LEFT JOIN Category T0 ON T.'PARENT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GreenCategory loadCurrentDeep(Cursor cursor, boolean lock) {
        GreenCategory entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        GreenCategory parent = loadCurrentOther(daoSession.getGreenCategoryDao(), cursor, offset);
        entity.setParent(parent);

        return entity;    
    }

    public GreenCategory loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GreenCategory> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GreenCategory> list = new ArrayList<GreenCategory>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GreenCategory> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GreenCategory> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
